version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            sudo apt install -y inotify-tools python python3
            tests/test.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
