name: CI

on:
  - push
  - pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout myself
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inotify-tools python2 python3
      - name: Run tests
        run: |
          tests/test.sh
